INSERT INTO LPROD(LPROD_ID,LPROD_GU,LPROD_NM)
VALUES(1,'F101','컴퓨터제품');
INSERT INTO LPROD(LPROD_ID,LPROD_GU,LPROD_NM)
VALUES(2, 'F102', '전자제품');
INSERT INTO LPROD(LPROD_ID,LPROD_GU,LPROD_NM)
VALUES(3,'F201','여성캐쥬얼');
INSERT INTO LPROD(LPROD_ID,LPROD_GU,LPROD_NM)
VALUES(4, 'F202', '남성캐쥬얼');
INSERT INTO LPROD(LPROD_ID,LPROD_GU,LPROD_NM)
VALUES(5,'F301','피혁잡화');
INSERT INTO LPROD(LPROD_ID,LPROD_GU,LPROD_NM)
VALUES(6, 'F302', '화장품');
INSERT INTO LPROD(LPROD_ID,LPROD_GU,LPROD_NM)
VALUES(7,'F401','음반/CD');
INSERT INTO LPROD(LPROD_ID,LPROD_GU,LPROD_NM)
VALUES(8,'F402','도서');
INSERT INTO LPROD(LPROD_ID,LPROD_GU,LPROD_NM)
VALUES(9, 'F403', '문구류');

SELECT *
FROM LPROD;

COMMIT;
--저장

--ROLLBACK; 
--최초 트랜잭션의 시작부분으로 돌아감(초기화)

SELECT LPROD_GU, LPROD_NM
FROM LPROD
WHERE LPROD_GU = 'F102';
--모든 작업 전 SELECT로 검수 해 볼것

UPDATE LPROD 
SET LPROD_NM = '향수'
WHERE LPROD_GU = 'F102';

COMMIT;

--
SELECT LPROD_GU, LPROD_NM
FROM LPROD
WHERE LPROD_GU = 'F202';

DELETE FROM LPROD
WHERE LPROD_GU = 'F202';

COMMIT;

ROLLBACK;

--상품 테이블로부터 모든 row와 columnn을 검색
SELECT *
FROM PROD;

--회원 테이블 모든 row, column
SELECT *
FROM MEMBER;

--특정 column
-- 회원 테이블에서 회원ID, 회원 이름 검색
SELECT MEM_ID,MEM_NAME
FROM MEMBER;

--상품 테이블로부터 상품코드, 상품명 검색
SELECT PROD_ID, PROD_NAME
FROM PROD;

--상품 테이블로부터 상품코드와 상품명을 검색
--단, 상품코드가 F10200000인 상품


--회원 테이블에 마일리지를12로 나눈 값을 검색
SELECT MEM_MILEAGE 마일리지, MEM_MILEAGE/12
FROM MEMBER;

--상품테이블의 상품코드, 상품명, 판매금액을 검색
--판매금액 = 판매단가(PROD_SALE)*55 로 계산
SELECT PROD_ID, PROD_NAME, PROD_SALE*55
FROM PROD;

--alias : 헤딩의 이름을 바꾸는 방법
SELECT MEM_MILEAGE 마일리지 --가장 많이 사용
     , MEM_MILEAGE/12 as 월평균 --그 다음 많이 사용
FROM MEMBER;

--상품테이블에서 PROD_ID, PROD_NAME, PROD_



