--거래처코드가 P30203과 동일지역에 속한 거래처만 검색
--Alias 거래처코드, 거래처, 주소
SELECt A.BUYER_ID 거래처코드
    ,  A.BUYER_NAME 거래처
    ,  A.BUYER_ADD1 ||' '|| A.BUYER_ADD2 주소
FROM BUYER A, BUYER B
WHERE B.BUYER_ID = 'P30203'
AND SUBSTR(A.BUYER_ADD1,1,2) = SUBSTR(B.BUYER_ADD1,1,2)
ORDER BY A.BUYER_ID;

--라준호 회원의 직업과 동일한 직업을 가진 회원의 리스트
--회원ID, 회원명, 직업
SELECT A.MEM_ID 회원ID
    ,  A.MEM_NAME 회원명
    ,  A.MEM_JOB 직업
FROM MEMBER A, MEMBER B
WHERE B.MEM_NAME LIKE '라준호'
AND A.MEM_JOB = B.MEM_JOB
ORDER BY A.MEM_ID;

--거래처 별 2005년도 거래현황
--결과가 0인 거래처에 대해서 다음 년도 계약 해지
--기초데이터 생성
--거래현황 : 입고가격의 합 SUM(PROD_COST)
--Alias 거래처ID, 거래처명, 거래현황
SELECT A.BUYER_ID
    ,  A.BUYER_NAME
    ,  NVL(SUM(B.PROD_COST),0)
FROM BUYER A, PROD B, BUYPROD C
WHERE A.BUYER_ID = B.PROD_BUYER(+)
AND B.PROD_ID = C.BUY_PROD(+)
AND C.BUY_DATE LIKE '05/%'
GROUP BY A.BUYER_ID, A.BUYER_NAME
ORDER BY A.BUYER_ID;

--ANSI (LEFT OUTER JOIN)
SELECT A.BUYER_ID 거래처ID
    ,  A.BUYER_NAME 거래처명
    ,  NVL(SUM(B.PROD_COST),0) 거래현황
FROM BUYER A LEFT OUTER JOIN PROD B ON A.BUYER_ID = B.PROD_BUYER
             LEFT OUTER JOIN BUYPROD C
             ON (B.PROD_ID = C.BUY_PROD AND C.BUY_DATE LIKE '05/%')
GROUP BY A.BUYER_ID, A.BUYER_NAME
ORDER BY A.BUYER_ID;

--2005년도 월별 모든 상품분류별
--매출 현황
--Alias 월(CART_NO) 상품분류(LPROD_NM) 매출금액(PROD_SALE*CART_QTY)
SELECT SUBSTR(CART_NO,5,2) 월
    ,  LPROD_NM 상품분류
    ,  SUM(PROD_SALE*CART_QTY) 매출금액
FROM LPROD LEFT OUTER JOIN PROD ON LPROD_GU = PROD_LGU
          LEFT OUTER JOIN CART ON  (CART_PROD = PROD_ID AND SUBSTR(CART_NO,1) LIKE '2005%')
GROUP BY SUBSTR(CART_NO,5,2), LPROD_NM
ORDER BY SUBSTR(CART_NO,5,2), SUM(PROD_SALE*CART_QTY) DESC;

--2005년도 판매된 상품 중 5회 이상의 판매횟수 있는 상품 조회
--상품코드, 상품명, 판매횟수
SELECT A.PROD_ID 상품코드
    ,  A.PROD_NAME 상품명
    ,  COUNT(CART_NO) 판매횟수
FROM   PROD A, CART B
WHERE  A.PROD_ID = B.CART_PROD
AND    CART_NO LIKE '2005%'
GROUP BY A.PROD_ID, A.PROD_NAME
HAVING COUNT(CART_NO) >= 5
ORDER BY A.PROD_ID;

--상품분류 컴퓨터제품(P101)인 상품의 2005년도 일차별 판매 조회
--판매일, 판매금액(5백만 초과인 경우만), 판매수량)
SELECT   TO_CHAR(TO_DATE(SUBSTR(CART_NO,1,8),'YYYYMMDD'),'YYYY"년" MM"월" DD"일"') 판매일
    ,    TO_CHAR(SUM(CART_QTY*PROD_SALE),'L999,999,999') 판매금액
    ,    SUM(CART_QTY) 판매수량
FROM     PROD, CART
WHERE    PROD_ID = CART_PROD
AND      CART_NO LIKE '2005%'
AND      PROD_LGU LIKE 'P101'
GROUP BY TO_CHAR(TO_DATE(SUBSTR(CART_NO,1,8),'YYYYMMDD'),'YYYY"년" MM"월" DD"일"')
HAVING   SUM(CART_QTY*PROD_SALE) > 5000000
ORDER BY 2 DESC;









