--2005년도 구매금액 2천만 이상 우수고객 지정 검색
--Alias 회원ID 회원명, 우수고객
--SUM(CART.CART_QTY*PROD.PROD_SALE)
SELECT D.MEM_ID 회원ID
    ,  D.MEM_NAME 회원명
    ,  SUM(E.CART_QTY*F.PROD_SALE) 우수고객
FROM MEMBER D, CART E, PROD F
WHERE D.CART_MEMBER = E.MEM_ID
AND D.CART_PROD = F.PROD_ID
AND SUM(E.CART_QTY*F.PROD_SALE) > 20000000
GROUP BY D.MEM_ID, D.MEM_NAME
;

SELECT M.MEM_ID 회원ID
     , M.MEM_NAME 회원명
     , '우수회원'
FROM   MEMBER M
WHERE  EXISTS 
(
       SELECT SUM(C.CART_QTY * P.PROD_SALE)
       FROM   CART C, PROD P
       WHERE  C.CART_PROD   = P.PROD_ID 
       AND    C.CART_MEMBER = M.MEM_ID
       AND    C.CART_NO LIKE '2005%'
       HAVING SUM(C.CART_QTY * P.PROD_SALE) > 20000000
);

--CRUD
--INSERT
CREATE TABLE REMAIN
(
    REMAIN_YEAR CHAR(04) NOT NULL,
    REMAIN_PROD VARCHAR2(10) NOT NULL,
    REMAIN_J_00 NUMBER(5),
    REMAIN_I NUMBER(5),
    REMAIN_O NUMBER(5),
    REMAIN_J_99 NUMBER(5),
    REMAIN_DATE DATE,
    CONSTRAINT PK_REMAIN PRIMARY KEY(REMAIN_YEAR, REMAIN_PROD),
    CONSTRAINT FR_REMAIN_PROD FOREIGN KEY(REMAIN_PROD)
                              REFERENCES PROD(PROD_ID)
);

--데이터의 개수와 컬럼의 개수가 모두 같은 경우
--Table전체 컬럼에 값을 입력
INSERT INTO REMAIN 
VALUES('2003','P101000001',20,10,12,18,'2004-01-01');

--위의 방법보다 아래와 같이 컬럼명을 기술하여 입력하는 방법을 권장한다
INSERT INTO REMAIN(REMAIN_YEAR,REMAIN_PROD,REMAIN_J_00,REMAIN_I,REMAIN_O,REMAIN_J_99,REMAIN_DATE)
VALUES ('2003','P101000002',11,7,6,12,'2004-01-02');

SELECT * FROM REMAIN;

INSERT INTO REMAIN REMAIN(REMAIN_YEAR,REMAIN_PROD,REMAIN_I)
VALUES ('2003','P102000007',10);

--NULL값 입력방법
--1) INSERT문장의 컬럼리스트에서 생략
INSERT INTO REMAIN(REMAIN_YEAR,REMAIN_PROD,REMAIN_J_00,REMAIN_I,REMAIN_O,REMAIN_J_99,REMAIN_DATE)
VALUES ('2003','P102000001',31,21,41,'2003-12-31');

--2) INSERT문장의 VALUES절에서 NULL 또는 빈공백 혹은 화이트 스페이스('')으로 지정
INSERT INTO REMAIN(REMAIN_YEAR,REMAIN_PROD,REMAIN_J_00,REMAIN_I,REMAIN_O,REMAIN_J_99,REMAIN_DATE)
VALUES ('2003','P102000002',31,21,NULL,41,'2003-12-31');

INSERT INTO REMAIN(REMAIN_YEAR,REMAIN_PROD,REMAIN_J_00,REMAIN_I,REMAIN_O,REMAIN_J_99,REMAIN_DATE)
VALUES ('2003','P102000003',31,21,'',41,'2003-12-31');

SELECT * FROM REMAIN;

COMMIT;

--INSERT
--REMAIN 테이블 데이터 입력
INSERT INTO REMAIN(REMAIN_YEAR,REMAIN_PROD,REMAIN_J_00,REMAIN_I,REMAIN_O,REMAIN_J_99,REMAIN_DATE)
VALUES ('2003','P302000023',31,'',20,15,SYSDATE);

--REMAIN테이블에 데이터 입력
--FK인 REMAIN_PROD에 없는 값을 참조할 수 없다
INSERT INTO REMAIN(REMAIN_YEAR,REMAIN_PROD,REMAIN_J_00, REMAIN_DATE)
VALUES ('2003','Z302000022',27,'2004-01-01');

--PK에 NULL값을 넣을 수 없다
INSERT INTO REMAIN(REMAIN_PROD, REMAIN_J_00, REMAIN_I, REMAIN_O, REMAIN_J_99, REMAIN_DATE)
VALUES ('P302000016',30,10,15,25,'2004-01-02');

SELECT * FROM REMAIN;

--
SELECT '2021', PROD_ID, SUBSTR(PROD_ID,-2), 10, 7, SUBSTR(PROD_ID,-2)+10-7
FROM PROD;

INSERT INTO REMAIN(REMAIN_YEAR,REMAIN_PROD,REMAIN_J_00,REMAIN_I,REMAIN_O,REMAIN_J_99)
SELECT '2021', PROD_ID, SUBSTR(PROD_ID,-2), 10, 7, SUBSTR(PROD_ID,-2)+10-7
FROM PROD;

SELECT *
FROM REMAIN
WHERE REMAIN_YEAR = '2021';

CREATE TABLE DAWICE
(
    DW_ACTINFO VARCHAR2(10) NOT NULL,
    DW_ACTYEAR VARCHAR2(20) NOT NULL,
    DW_MEMBER VARCHAR2(60),
    DW_SITE VARCHAR2(40),
    CONSTRAINT PK_DAWICE PRIMARY KEY(DW_ACTINFO)
);

--데이터 입력
INSERT INTO DAWICE (DW_ACTINFO, DW_ACTYEAR, DW_MEMBER, DW_SITE)
VALUES ('BAEKHYUN', '2017', '변백현', 'http://www.smtown.com');

SELECT * FROM DAWICE;

--컬럼 데이터 입력
INSERT INTO DAWICE (DW_ACTINFO, DW_ACTYEAR, DW_MEMBER)
VALUES ('KRIS', '2017', '크리스');

--테이블 복제
CREATE TABLE DAWICE2
AS
SELECT * FROM DAWICE;

SELECT * FROM DAWICE2;

--TABLE 앞에 쓰이는 DESC는 TABLE 내의 구조형태를 보여준다
DESC DAWICE2;

DELETE FROM DAWICE2;

COMMIT;

--SELECT문으로 넣으려는 값을 찾은 후 SELECT문 위에 INSERT INTO 를 넣어 값을 저장할 수 있다
INSERT INTO DAWICE2(DW_ACTINFO, DW_ACTYEAR, DW_MEMBER, DW_SITE)
SELECT DW_ACTINFO
    ,  DW_ACTYEAR
    ,  DW_MEMBER
    ,  DW_SITE
FROM DAWICE;

CREATE TABLE TB_JDBC_BOARD
(
BOARD_NO NUMBER(5) NOT NULL,
TITLE VARCHAR2(10),
CONTENT VARCHAR2(10),
USER_ID VARCHAR2(10),
REG_DATE DATE
);

select * from TB_JDBC_BOARD;